wp_waypoint:
  ros__parameters:
    area: ["area1", "area2", "area3"]
    area1:
      area_:
      - {x: -2., y: -2.}
      - {x: -2., y: 0.}
      - {x: 0., y: 0.}
      - {x: 0., y: -2.}
      - {x: -2., y: -2.}
      transform_area_:
      - {x: -2., y: -2.}
      - {x: -2., y: -1.}
      - {x: -1.5, y: -1.}
      - {x: -1.5, y: -2.}
      - {x: -2., y: -2.}
      shape_: "i"
      target_: [-0.4, -0.17]
    area2:
      area_:
      - {x: -2., y: 0.}
      - {x: -2., y: 2.}
      - {x: 0.5, y: 0.}
      - {x: 0.5, y: 2.}
      - {x: -2., y: 0.}
      transform_area_:
      - {x: -.1, y: 0}
      - {x: 0., y: 0}
      - {x: 0., y: -0.5}
      - {x: -.1, y: -0.5}
      - {x: -.1, y: 0}
      shape_: "o"
      target_: [0.2, 1.45]

    area3:
      area_:
      - {x: 0.5, y: 0}
      - {x: 0.5, y: 2}
      - {x: 2, y: 2}
      - {x: 2, y: 0}
      - {x: 0.5, y: 0}
      transform_area_:
      - {x: 0, y: 1.2}
      - {x: 0, y: 2}
      - {x: 0.5, y: 2}
      - {x: 0.5, y: 1.2}
      - {x: 0, y: 1.2}
      shape_: "i"
      target_: [1.45, 0.2]

